# 1. NumPy Giriş

## 1.1. Numerical Python'suz yapılan array işlemi

In [1]:
a  = [1,2,3,4]
b  = [2,3,4,5]

ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

-------------------------------------------------------------------------

## 1.2. Numerical Python(NumPy) ile yapılınca

In [32]:
# 'numpy' kütüphanesini daha rahat kullanabilmek için geleneksel olarak np haline getirdik.
# Bundan sonra numpy yerine 'np' kullanacağız
import numpy as np

# 'numpy' arrayini(vektör) oluşturmuş olduk. Elimizdeki listeyi vektöre çevirdik.
a = np.array([1,2,3,4])

# 'numpy' arrayini(vektör) oluşturmuş olduk. Elimizdeki listeyi vektöre çevirdik.
b = np.array([2,3,4,5])

# skaler çarpımın indeksleri : çıkan sonuçte bize verilen arrayin(vektörün) içindeki bileşenleri
# topladığımızda skaler çarpımı elde etmiş oluruz.
a * b                   

array([ 2,  6, 12, 20])

-----------------------------------------------------------------------------

## 1.3. Python'da bir integerın yada bir listenin maliyeti hakkında bilgi

In [2]:
"""
Standart python C dili ile yazılmıştır. 
Bu durum veri tipleri anlamında python nesnelerinin biz görmesekte,
bazı gizli c özneleri barındırdığını ifade eder.
"""

'\nStandart python C dili ile yazılmıştır. \nBu durum veri tipleri anlamında python nesnelerinin biz görmesekte,\nbazı gizli c özneleri barındırdığını ifade eder.\n'

In [3]:
# Python, C deki yapıları bize basitleştirerek sunar.

In [4]:
x = 9

In [5]:
# who komutu bize yazdığımız kodun içinde bulunan bütün değişkenleri gösterir.

In [6]:
who

a	 ab	 b	 i	 x	 


In [7]:
x

9

In [8]:
L = [1,2,"a",1.2]        # bu durum pythonın sevdiğimiz yanlarından. birbirinden farklı tipleri esnekçe kolayca bir arada tutabiliyoruz.
[type(i) for i in L]     # fakat böyle kolayca kullanmak bize kapladığı alan bakımından çok maliyetli. Bu sebepten dolayı listeler yerine
                         # numpy arraylerini kullanarak daha ergonomik bir kod yazmamız bizim işimize geliyor.

[int, int, str, float]

-----------------------------------------------------------------

# 2. Numpy Arrayleri Oluşturmak

## 2.1. Listelerden Array Oluşturmak

In [9]:
import numpy as np

np.array([12,33,4,5])      # bu fonksiyonun görevi liste üzerinden bir numpy arrayi oluşturmak.

a = np.array([12,33,4,5])

a

type(a)

numpy.ndarray

In [10]:
np.array([3.14, 4, 6, 1.2])   # outputa baktığımızda bütün değerler ondalık olarak ifade edilmiş.

array([3.14, 4.  , 6.  , 1.2 ])

In [11]:
np.array([3.14, 4, 6, 1.2], dtype = 'float32')  # dtype yazarak kendi veri tipimizi ifade edebiliriz.

array([3.14, 4.  , 6.  , 1.2 ], dtype=float32)

In [12]:
np.zeros(10, dtype = 'int')  # 10 tane sıfırdan oluşan integer bir array.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10)  # 10 tane 1 den oluşan ondalık bir array.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((2,3)) # 2 x 3 matris boyutunda bütün bileşenleri ondalık biçimde 1 olan bir array.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.full((2,3),9)  # 2 x 3 matris boyutunda bütün bileşenleri 9 olan bir array.

array([[9, 9, 9],
       [9, 9, 9]])

In [16]:
np.arange(0,10,2)  # 0'dan 10'a kadar 2 değer artacak biçimde oluşturulmuş bir array.

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(0,1,30)  # 0 ve 1 arasında aralarındaki mesafe eşit olacak bir biçimde 30 tane oluşturulmuş bir array.

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [53]:
np.random.normal(0,1,(3,4))  # burada 0 kitlenin standart ortalamasını, 1 varyansını, (3,4) 3 x 4 lük bir matrisi ifade eder.

array([[ 0.09361079,  1.09264321, -0.04341667,  0.55623281],
       [ 0.350653  , -0.76783208, -1.36304043, -0.88924653],
       [ 1.39457408,  1.56214398, -0.31975736, -0.10668128]])

In [56]:
np.random.randint(0,10,(2,2))  # 0 ile 10 arasında 2 x 2 lik matrise göre rastgele 4 tane integer bileşenini array olarak ifade eder.

array([[9, 4],
       [4, 4]])

In [58]:
np.eye(3)  # 3 x 3 lük birim matrisi ondalık biçimde ifade eder.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

-------------------------------------------------------

## 2.2. Numpy Biçimlendirme

* **ndim**  : boyut sayısı
* **shape** : boyut bilgisi
* **size**  : toplam eleman sayısı
* **dtype** : array veri tipi

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([9, 6, 2, 1, 4, 2, 9, 0, 1, 1])

In [2]:
a.ndim  # 1 boyutlu

1

In [3]:
a.shape  # boyutun içerisindeki sayıyı verdi.

(10,)

In [4]:
a.size  # arrayin büyüklüğü

10

In [5]:
a.dtype  # arrayin içerisindeki verinin yapısı

dtype('int32')

In [7]:
b = np.random.randint(10, size = (10, 5))  # 10 x 5 matrislik olacak şekilde 
b

array([[7, 5, 4, 9, 2],
       [6, 5, 6, 9, 4],
       [0, 4, 5, 2, 1],
       [9, 4, 1, 0, 6],
       [0, 3, 5, 6, 6],
       [2, 6, 8, 1, 4],
       [2, 1, 2, 3, 5],
       [2, 8, 9, 4, 5],
       [8, 0, 7, 1, 7],
       [3, 1, 8, 3, 9]])

In [8]:
b.ndim  # 2 boyutlu

2

In [9]:
b.shape  # matrisin satır ve sütün sayısı

(10, 5)

In [10]:
b.shape[0]

10

In [14]:
b.shape[1]

5

In [74]:
b.size  # matrisin içerisindeki bileşen sayısı : 10 x 5 olduğundan 50 tane.

50

In [75]:
b.dtype  # arrayin içerisindeki verinin yapısı

dtype('int32')

In [80]:
c = np.random.randint(10, size = (3,5,2))  # 0 ile 10 arasındaki rastgele integerların 3 x 5 x 2 matris olacak şekilde gösterilişi
c                                          # 3 adet 5 x 2 matris

array([[[2, 1],
        [6, 2],
        [7, 4],
        [4, 5],
        [2, 7]],

       [[5, 0],
        [3, 8],
        [7, 5],
        [3, 6],
        [6, 9]],

       [[8, 7],
        [6, 6],
        [1, 1],
        [4, 0],
        [2, 6]]])

In [78]:
c.ndim

3

In [79]:
c.shape

(3, 5, 2)

In [81]:
c.size

30

In [82]:
c.dtype

dtype('int32')

--------------------------------------------------------------------------

## 2.3. Biçimlendirmek, Yeniden Şekillendirmek

In [88]:
np.arange(1,10)  # 1 den 10 a kadar bütün integerları 1 boyutlu arrayde gösterme

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(1,10).reshape((3,3))  # 9 elemanlı reshape kullanarak 3 x 3 lük bir matris oluşturma

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
x = np.array([1,2,3])  # tek boyurlu bir array
x

array([1, 2, 3])

In [92]:
y = x.reshape((1,3))  # bunu reshape ile 1 x 3 lük bir dönüştürme işlemine tuttuğumda, bu artık 2 boyutlu bir matris olmuş olur.
y

array([[1, 2, 3]])

In [93]:
y.ndim

2

In [98]:
x[np.newaxis, :]  # arrayi 1 x 3 olarak(2 boyutlu) gösterme, satır vektörü

array([[1, 2, 3]])

In [106]:
x[:, np.newaxis]  # arrayi 3 x 1 olarak(2 boyutlu) gösterme, kolon vektörü

array([[1],
       [2],
       [3]])

---------------------------------------------------

## 2.4. Biçimlendirmek, Birleştirmek

### 2.4.1. Tek boyutlu

In [107]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [108]:
np.concatenate([x,y])   # iki adet arrayi ucuca ekler.

array([1, 2, 3, 4, 5, 6])

In [109]:
z = [1,2,3]
np.concatenate([x,y,z])  # z listesini de arraye aynı şekilde ekliyebiliriz.

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

### 2.4.2. İki boyutlu

In [111]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
np.concatenate([a,a])   # a vektörünü kendisini kolon bazında array olarak birleştirdik.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [114]:
np.concatenate([a,a],axis = 1)   # a arrayini kendisiyle satır bazında array olarak birleştirdik.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### 2.4.3. Farklı boyutlu

In [127]:
a = np.array([1,2,3])
b = np.array([[9,8,7],[6,5,4]])  # boyutları birbirinden farklı

In [128]:
np.vstack([a,b])  # boyutları birbirleriyle örtüşmeyen iki arrayi kolon bazında birleştirme.(kolon boyutlarının aynı olması gerekir.)

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [129]:
a = np.array([[99],[99]])
b = np.array([[9,8,7],[6,5,4]])

In [130]:
np.hstack([a,b])   # boyutları birbirleriyle örtüşmeyen iki arrayi satır bazında birleştirme.(satır boyutları aynı olması gerekir.)

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

-----------------------------------------------

## 2.5. Biçimlendirmek, Ayırmak (Array Splitting)

In [131]:
x = [1,2,3,99,99,3,2,1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [134]:
np.split(x,[3,5])   # x arrayini 0-1-2, 3-4-5, ve geri kalan olacak şekilde üç parçaya array olarak böldük.

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [135]:
a,b,c = np.split(x,[3,5])  # x arayini 3 parçaya ayırdıktan sonra a,b,c olarak her bir bileşeni birbirine eşitliyebiliriz.

In [136]:
a

array([1, 2, 3])

In [137]:
b

array([99, 99])

In [138]:
c

array([3, 2, 1])

In [139]:
np.arange(16).reshape((4,4))  # 0 dan 15 e kadar olacak şekilde 4 x 4 lük bir matris oluşturduk.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [156]:
m = np.arange(16).reshape((4,4))

In [157]:
np.vsplit(m, [2])  # m arrayini 0. ve 1. satırlarını ayrı bir array olarak ayırdıktan sonra, kalan kısmı da ayrı bir array olarak ayırmış olduk.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [167]:
ust, alt = np.vsplit(m, [2])  # m arrayininin ilk iki satırı 'ust' ve kalan satırları 'alt' arrayleri olacak şekilde ayırdık.

In [168]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [169]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [170]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [171]:
np.hsplit(m, [2])  # m arrayinin 0. ve 1. kolonlarını ayrı bir array olarak ayırdıktan sonra, kalan kısmı da ayrı bir array olarak ayırmış olduk.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [172]:
n = np.hsplit(m, [2])

In [173]:
sol, sag = np.hsplit(m, [2])  # m arrayininin ilk iki kolonunu 'sol' ve kalan kolonları 'sag' arrayleri olacak şekilde ayırdık.

In [174]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [175]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

-----------------------------------------------

## 2.6. Biçimlendirmek, Sıralamak

In [176]:
v = np.array([2,1,4,3,5])

In [179]:
np.sort(v)  # v arrayini küçükten büyüğe göre yeni bir array olacak şekilde sıralar.

array([1, 2, 3, 4, 5])

In [183]:
i = np.argsort(v)  # v arrayinin 0. indexinde bulunan '2' değeri 'sort' ile yazılan arrayin 1. indexine gitmiştir.

In [181]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [184]:
v[i]

array([1, 2, 3, 4, 5])

In [186]:
import numpy as np
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [187]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

-----------------------------------------

# 3. NumPy Eleman İşlemleri

## 3.1. Index

In [190]:
import numpy as np
a = np.random.randint(0,10, size = 10)  # arrayi 0 dahil 0 ve 10 arasındaki 10 tane integerı, 10 tane index alıcak biçimde 'a' arrayine atar.
a

array([7, 4, 7, 0, 9, 7, 7, 3, 1, 9])

In [192]:
a[0]  # 0. indexdeki değeri gösterir.

7

In [193]:
a[-1]  # en son indexdeki değeri gösterir.

9

In [194]:
a[-2]  # sondan 2. yada tersten 2. indexdeki değeri gösterir.

1

In [195]:
a[0] = 1

In [196]:
a

array([1, 4, 7, 0, 9, 7, 7, 3, 1, 9])

In [198]:
a = np.random.randint(10, size = (3,5))
a

array([[2, 8, 7, 2, 3],
       [6, 5, 6, 3, 1],
       [6, 8, 2, 9, 7]])

In [199]:
a[0][0]

2

In [200]:
a[0,0]

2

In [201]:
a[1,1]

5

In [202]:
a[0,0] = 1

In [203]:
a

array([[1, 8, 7, 2, 3],
       [6, 5, 6, 3, 1],
       [6, 8, 2, 9, 7]])

In [212]:
a[0,0] = 2.2  # 2.2 yazmamıza rağmen integer olarak algılar. Çünkü kodun her bileşeni için veri tipi tutmaması için
a             # ergonomik olmasından dolayı bit tipli bir veri kullanılır.


array([[2, 8, 7, 2, 3],
       [6, 5, 6, 3, 1],
       [6, 8, 2, 9, 7]])

--------------------------------------

## 3.2. Slice

In [214]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [215]:
a[0:3]

array([20, 21, 22])

In [216]:
a[:3]

array([20, 21, 22])

In [217]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [218]:
a[::2]

array([20, 22, 24, 26, 28])

In [220]:
a[1::2]  # 1. indexden başla 2 şer 2 şer ilerle

array([21, 23, 25, 27, 29])

In [221]:
a[1::3]

array([21, 24, 27])

In [224]:
a = np.random.randint(10, size = (5,5))
a

array([[5, 8, 3, 2, 4],
       [3, 7, 0, 2, 0],
       [6, 6, 1, 8, 6],
       [9, 0, 9, 6, 8],
       [2, 3, 6, 9, 5]])

In [225]:
a[:,0]

array([5, 3, 6, 9, 2])

In [226]:
a[:,1]

array([8, 7, 6, 0, 3])

In [227]:
a[:,4]

array([4, 0, 6, 8, 5])

In [228]:
a[0,:]

array([5, 8, 3, 2, 4])

In [229]:
a[0]

array([5, 8, 3, 2, 4])

In [230]:
a[4]

array([2, 3, 6, 9, 5])

In [231]:
a[:2,:3]

array([[5, 8, 3],
       [3, 7, 0]])

In [232]:
a[0:2,0:3]

array([[5, 8, 3],
       [3, 7, 0]])

In [235]:
a[::,:2]

array([[5, 8],
       [3, 7],
       [6, 6],
       [9, 0],
       [2, 3]])

In [236]:
a[:]

array([[5, 8, 3, 2, 4],
       [3, 7, 0, 2, 0],
       [6, 6, 1, 8, 6],
       [9, 0, 9, 6, 8],
       [2, 3, 6, 9, 5]])

In [237]:
a[1:3,0:2]

array([[3, 7],
       [6, 6]])

In [245]:
x = np.random.randint(0,10,size=(5,5))

In [246]:
alt_x = x[0:3,0:2]  # x in içerisinde alt küme belirledik.
alt_x

array([[0, 2],
       [5, 8],
       [2, 2]])

In [241]:
alt_x[0,0]=9999  # x in içerisinde belirlediğimiz altkümelerin indislerini değiştirdik.
alt_x[1,1]=9999

In [242]:
alt_x   # indisleri değiştirildikten sonraki altkümenin hali

array([[9999,    2],
       [   7, 9999],
       [   2,    1]])

In [243]:
x  # fakat görünen o ki alt kümedeki indisleri değiştirdiğimizde kümenin kendisinde de yani x arrayinde de değişiklik yapılmış oldu.

array([[9999,    2,    5,    0,    5],
       [   7, 9999,    1,    3,    2],
       [   2,    1,    0,    0,    6],
       [   7,    9,    2,    1,    5],
       [   3,    4,    7,    2,    0]])

In [248]:
x = np.random.randint(0,10,size=(5,5))
alt_x = x[0:3,0:2].copy()   # bu neden dolayı alt kümeyi farklı bir indis olarak göstermek amacıyla 'copy' fonksiyonunu kullanıyoruz. ÇOK ÖNEMLİ !!!

In [250]:
x

array([[8, 3, 9, 9, 3],
       [3, 7, 9, 8, 3],
       [8, 0, 9, 9, 7],
       [4, 3, 8, 9, 5],
       [0, 2, 7, 3, 8]])

In [251]:
alt_x

array([[8, 3],
       [3, 7],
       [8, 0]])

In [252]:
alt_x[0,0]=9999  # x in içerisinde belirlediğimiz altkümelerin indislerini yeniden değiştirdik.
alt_x[1,1]=9999

In [253]:
alt_x   # indisleri değiştirildikten sonraki altkümenin hali

array([[9999,    3],
       [   3, 9999],
       [   8,    0]])

In [255]:
x   # görüldüğü üzere x arrayinde bir değişiklik yapılmamış oldu.

array([[8, 3, 9, 9, 3],
       [3, 7, 9, 8, 3],
       [8, 0, 9, 9, 7],
       [4, 3, 8, 9, 5],
       [0, 2, 7, 3, 8]])

--------------------------------------

## 3.3. Fancy Index

In [256]:
v = np.arange(0,30,3)

In [257]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [259]:
[v[1],v[3]]

[3, 9]

In [260]:
al_getir = [1,3,5]

In [261]:
v[al_getir]

array([ 3,  9, 15])

In [262]:
v[[1,3,5]]

array([ 3,  9, 15])

In [263]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [265]:
m = np.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [266]:
m[satir,sutun]

array([1, 5])

In [267]:
m[0,[1,2]]  # m arrayinin içerisinde 0. satır 1. sutun ve 0. satır 2. sutun indexlerini bir arrayin içerisinde bize belirtir.

array([1, 2])

In [269]:
m[0:,[1,2]]  # m arrayinin 0. satırdan son satıra kadarı ile 1. ve 2. sutunlarını bir array içerisinde gösterir.

array([[1, 2],
       [4, 5],
       [7, 8]])

In [270]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
index = np.array([0,1,2])
v[index]

array([0, 1, 2])

In [276]:
v[index] = 99  # v arrayinin 0.,1., ve 2. indexlerinin hepsini 99 a işaretler.

In [277]:
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [278]:
v[[0,1]] = [4,6]  # v arrayinin 0. ve 1. indexlerini sırasıyla 4 ve 6 olarak değiştirir.

In [279]:
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

In [281]:
v[index] = [99,90,95]  # v arrayinin 0., 1., ve 2. yani 'index' indexlerini sırasıyla 99, 90, 85 olarak değiştirir.

In [282]:
v

array([99, 90, 95,  3,  4,  5,  6,  7,  8,  9])

-------------------------

## 3.4. Koşullu Eleman İşlemleri

In [2]:
import numpy as np
v = np.array([1,2,3,4,5])

array([False, False, False,  True,  True])

In [5]:
v > 3

array([False, False, False,  True,  True])

In [4]:
v < 3

array([ True,  True, False, False, False])

In [6]:
v == 3

array([False, False,  True, False, False])

In [7]:
v != 3

array([ True,  True, False,  True,  True])

In [8]:
(2 * v)

array([ 2,  4,  6,  8, 10])

In [9]:
(v ** 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [10]:
(2 * v) == (v ** 2)

array([False,  True, False, False, False])

In [11]:
np.equal
np.not_equal
np.less
np.less_equal
np.greater
np.greater_equal

<ufunc 'greater_equal'>

In [12]:
v = np.array([1,2,3,4,5])
np.equal(3,v)  # v arrayinde 3 e eşit olan array bileşenlerini boolean olarak belirtir.

array([False, False,  True, False, False])

In [16]:
np.arange(3)

array([0, 1, 2])

In [17]:
np.equal([0,1,3], np.arange(3))

array([ True,  True, False])

In [19]:
v = np.random.randint(0, 10, (3 ,3))
v

array([[1, 0, 0],
       [7, 7, 9],
       [8, 9, 9]])

In [20]:
v > 5  # v matrisinin/arrayinin 5 den büyük olan bileşenlerini boolean olarak ifade eder.

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
np.sum(v > 5)  # v arrayinin 5 den büyük olan değerlerini sayar.

6

In [24]:
np.sum((v > 3) & (v < 7))  # v arrayinin 3 den büyük ve 7 den küçük olan bileşenlerini sayar.

0

In [25]:
(v > 3) & (v < 7)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [26]:
np.sum((v > 3) | (v < 7))

9

In [28]:
np.sum(v > 4, axis = 1)  # v arrayinin satır bazında sırasıyla 4 den büyük olan bileşenlerini sayar.

array([0, 3, 3])

In [29]:
np.sum(v < 4, axis = 0)  # v arrayinin kolon bazında sırasıyla 4 den büyük olan bileşenlerini sayar.

array([1, 1, 1])

In [30]:
np.all(v > 4)   # v arrayinin içerisindeki bileşenlerin hepsi 4 den büyük mü olarak boolean ifade eder.

False

In [32]:
np.all(v >= 0)

True

In [33]:
np.any(v > 4)   # v arrayinin içerisindeki bileşenlerden herhangi biri 4 den büyük ise 'True' olarak belirtir.

True

In [37]:
np.any(v > 4, axis = 0)   # v arrayinin her bir kolonuna bakar ve kolon bileşenlerinde 4 den büyük değer varsa 'True' olarak belirtir.

array([ True,  True,  True])

In [36]:
np.any(v > 4, axis = 1)   # v arrayinin her bir satırına bakar ve kolon bileşenlerinde 4 den büyük değer varsa 'True' olarak belirtir.

array([False,  True,  True])

In [40]:
v = np.arange(1,6)
v

array([1, 2, 3, 4, 5])

In [41]:
v > 3

array([False, False, False,  True,  True])

In [42]:
v[v > 3]

array([4, 5])

In [43]:
v[(v > 1) & (v < 5)]

array([2, 3, 4])

---------------------------------------

## 3.5. Matematiksel İşlemler

In [45]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [46]:
a - 1   # a arrayinin herbir bileşeninden 1 değerini çıkarır.

array([-1,  0,  1,  2,  3])

In [47]:
a / 2   # a arrayinin herbir bileşenini 2 ye böler.

array([0. , 0.5, 1. , 1.5, 2. ])

In [48]:
a * 5   # a arrayinin herbir bileşenini 5 ile çarpar.

array([ 0,  5, 10, 15, 20])

In [49]:
a ** 2   # a arrayinin herbir bileşeninin 2. üssünü alır.

array([ 0,  1,  4,  9, 16], dtype=int32)

In [50]:
a % 2   # a arrayinin herbir bileşeninin 2 ye bölümünden kalanlarını array olarak gösterir.

array([0, 1, 0, 1, 0], dtype=int32)

In [51]:
5 * (a / 2 * 9)  # a arrayini 5 ile çarpar, 2 ye böler, sonra da 9 ile çarpar ve array olarak gösterir.

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [52]:
np.add(a,2)  # a arrayinin her bir elemanına 2 ekler.

array([2, 3, 4, 5, 6])

In [56]:
np.subtract(a,1)  # a arrayinin her bir elemanından 1 çıkarır.

array([-1,  0,  1,  2,  3])

In [57]:
np.multiply(a,3)  # a arrayinin her bir elemanını 3 ile çarpar.

array([ 0,  3,  6,  9, 12])

In [58]:
np.divide(a,3)   # a arrayinin her bir elemanını 3 e böler.

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [59]:
np.power(a,3)   # a arrayinin her bir elemanının 3. kuvvetini alır.

array([ 0,  1,  8, 27, 64], dtype=int32)

In [60]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [61]:
np.add.reduce(a)

15

In [62]:
np.sum(a)

15

In [64]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [65]:
a = np.random.normal(0,1,30)

In [66]:
np.mean(a)   # a arrayinin aritmetik ortalamasını alır.

0.38418260060430753

In [67]:
np.std(a)   # a arrayinin standart sapmasını alır.

1.1094450339487394

In [68]:
np.var(a)  # a arrayinin varyansını alır.

1.2308682833535196

In [69]:
np.median(a)

0.2520636889171627

In [70]:
np.min(a)

-1.8821428122471704

In [71]:
np.max(a)

2.124436193278382

In [76]:
import numpy as np
a = np.random.normal(0, 1, (3,3))
a

array([[-1.96196912, -0.16049586,  1.1807108 ],
       [-0.09320445, -0.15990543,  0.4698514 ],
       [-0.51658308,  0.12163959,  0.62873536]])

In [77]:
a.sum()

-0.49122077679511844

In [78]:
a.sum(axis = 0)

array([-2.57175665, -0.19876169,  2.27929756])

In [79]:
a.sum(axis = 1)

array([-0.94175418,  0.21674153,  0.23379187])

In [80]:
np.sum(a, axis = 0)

array([-2.57175665, -0.19876169,  2.27929756])

In [81]:
np.sum(a, axis = 1)

array([-0.94175418,  0.21674153,  0.23379187])

--------------------------------

## 3.6. Array Birleştirme(Broadcasting)

In [82]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,2,3])

In [83]:
a + b

array([2, 4, 6])

In [84]:
m = np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
a

array([1, 2, 3])

In [87]:
a + m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [92]:
a = np.arange(3)
a

array([0, 1, 2])

In [91]:
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [90]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [93]:
M = np.ones((2,3))
N = np.arange(3)

In [95]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [96]:
N

array([0, 1, 2])

In [97]:
M + N

array([[1., 2., 3.],
       [1., 2., 3.]])

In [100]:
x = np.arange(3).reshape(3,1)
x

array([[0],
       [1],
       [2]])

In [101]:
y = np.arange(3)
y

array([0, 1, 2])

In [102]:
x.shape

(3, 1)

In [103]:
y.shape

(3,)

In [104]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [105]:
x1 = np.ones((3,2))
x1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [106]:
y1 = np.arange(3)
y1

array([0, 1, 2])

In [108]:
x1.shape

(3, 2)

In [109]:
y1.shape

(3,)

In [110]:
x1 + y1

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

------------------------------------

## 3.7. Yapısal Arrayler

In [111]:
isim = ['ali', 'veli', 'isik']
yas = [25, 22, 19]
boy = [168, 159, 172]

In [112]:
data = np.zeros(3, dtype = {'names':('isim', 'yas', 'boy'), 'formats':('U10', 'i4', 'f8')})

In [113]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [114]:
data['isim'] = isim
data['yas'] = yas
data['boy'] = boy

In [115]:
data

array([('ali', 25, 168.), ('veli', 22, 159.), ('isik', 19, 172.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [116]:
data[data['yas'] < 25]['isim']

array(['veli', 'isik'], dtype='<U10')