# Yapay Sinir Ağları (YSA)

İnsan beyninin bilgi işleme şeklini referans alan,

sınıflandırma ve regresyon problemleri için kullanılabilen,

kuvvetli makine öğrenmesi algoritmalarından birisidir.

--------

# 1. Model (YSA)

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import scale 
from sklearn import model_selection
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

from warnings import filterwarnings
filterwarnings('ignore')

In [13]:
hit = pd.read_csv("Hitters.csv")

df = hit.copy()

df = df.dropna()

In [14]:
df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   
5    594   169      4    74   51     35     11    4408   1133      19    501   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N  
5   336     194      A        W      282      421      25   750.0         A

In [15]:
dms = pd.get_dummies(df[["League", "Division", "NewLeague"]])

dms.head()

League_A  League_N  Division_E  Division_W  NewLeague_A  NewLeague_N
1         0         1           0           1            0            1
2         1         0           0           1            1            0
3         0         1           1           0            0            1
4         0         1           1           0            0            1
5         1         0           0           1            1            0

In [16]:
X_ = df.drop(["Salary", "League", "Division", "NewLeague"], axis = 1).astype("float64")

X_.head()

AtBat   Hits  HmRun  Runs   RBI  Walks  Years  CAtBat   CHits  CHmRun  \
1  315.0   81.0    7.0  24.0  38.0   39.0   14.0  3449.0   835.0    69.0   
2  479.0  130.0   18.0  66.0  72.0   76.0    3.0  1624.0   457.0    63.0   
3  496.0  141.0   20.0  65.0  78.0   37.0   11.0  5628.0  1575.0   225.0   
4  321.0   87.0   10.0  39.0  42.0   30.0    2.0   396.0   101.0    12.0   
5  594.0  169.0    4.0  74.0  51.0   35.0   11.0  4408.0  1133.0    19.0   

   CRuns   CRBI  CWalks  PutOuts  Assists  Errors  
1  321.0  414.0   375.0    632.0     43.0    10.0  
2  224.0  266.0   263.0    880.0     82.0    14.0  
3  828.0  838.0   354.0    200.0     11.0     3.0  
4   48.0   46.0    33.0    805.0     40.0     4.0  
5  501.0  336.0   194.0    282.0    421.0    25.0

In [17]:
X = pd.concat([X_, dms[["League_N", "Division_W", "NewLeague_N"]]], axis = 1)

X.head()

AtBat   Hits  HmRun  Runs   RBI  Walks  Years  CAtBat   CHits  CHmRun  \
1  315.0   81.0    7.0  24.0  38.0   39.0   14.0  3449.0   835.0    69.0   
2  479.0  130.0   18.0  66.0  72.0   76.0    3.0  1624.0   457.0    63.0   
3  496.0  141.0   20.0  65.0  78.0   37.0   11.0  5628.0  1575.0   225.0   
4  321.0   87.0   10.0  39.0  42.0   30.0    2.0   396.0   101.0    12.0   
5  594.0  169.0    4.0  74.0  51.0   35.0   11.0  4408.0  1133.0    19.0   

   CRuns   CRBI  CWalks  PutOuts  Assists  Errors  League_N  Division_W  \
1  321.0  414.0   375.0    632.0     43.0    10.0         1           1   
2  224.0  266.0   263.0    880.0     82.0    14.0         0           1   
3  828.0  838.0   354.0    200.0     11.0     3.0         1           0   
4   48.0   46.0    33.0    805.0     40.0     4.0         1           0   
5  501.0  336.0   194.0    282.0    421.0    25.0         0           1   

   NewLeague_N  
1            1  
2            0  
3            1  
4            1  
5            0

In [18]:
y = df["Salary"]

y.head()

1    475.0
2    480.0
3    500.0
4     91.5
5    750.0
Name: Salary, dtype: float64

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [22]:
scaler = StandardScaler()

scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [23]:
X_train_scaled = scaler.transform(X_train)

In [24]:
X_test_scaled = scaler.transform(X_test)

In [25]:
mlp_model = MLPRegressor().fit(X_train_scaled, y_train)

In [26]:
mlp_model

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100,), learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=None, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [32]:
mlp_model.n_layers_  # 3 katman var - giriş katmanı, gizli katman, çıkış katmanı

3

In [33]:
mlp_model.hidden_layer_sizes  # gizli katman sayısı - hidden layer

(100,)

In [36]:
mlp_model = MLPRegressor(hidden_layer_sizes = (100, 20)).fit(X_train_scaled, y_train)

In [39]:
mlp_model.n_layers_  # 4 katman var - giriş katmanı, 2 gizli katman, çıkış katmanı

4

In [40]:
mlp_model.hidden_layer_sizes  # gizli katman sayısı - hidden layer

(100, 20)

--------------

# 2. Tahmin (YSA)

In [41]:
mlp_model.predict(X_train_scaled)[0:5]

array([ 73.84492058, 337.54700984, 230.03907996,  47.85736456,
        50.85145862])

In [42]:
mlp_model.predict(X_test_scaled)[0:5]

array([158.91939771, 280.60891059, 505.57885675, 101.80177727,
       159.78257996])

In [44]:
y_pred_train = mlp_model.predict(X_train_scaled)

In [45]:
y_pred_test = mlp_model.predict(X_test_scaled)

In [46]:
np.sqrt(mean_squared_error(y_test, y_pred_test))

477.82627479930727

-------------

# 3. Model Doğrulama / Model Tuning (YSA)

In [47]:
mlp_model

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100, 20), learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=None, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [51]:
mlp_params = {"alpha" : [0.1, 0.01, 0.02, 0.05, 0.005],
             "hidden_layer_sizes" : [(20, 20), (100, 50, 150), (300, 200, 150)],
             "activation" : ["relu", "logistic"]}

In [52]:
mlp_cv_model = GridSearchCV(mlp_model, mlp_params, cv = 10)

mlp_cv_model.fit(X_train_scaled, y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=MLPRegressor(activation='relu', alpha=0.0001,
                                    batch_size='auto', beta_1=0.9, beta_2=0.999,
                                    early_stopping=False, epsilon=1e-08,
                                    hidden_layer_sizes=(100, 20),
                                    learning_rate='constant',
                                    learning_rate_init=0.001, max_iter=200,
                                    momentum=0.9, n_iter_no_change=10,
                                    nesterovs_momentum=True, power_t=0.5,
                                    random_state=None, shuffle=True,
                                    solver='adam', tol=0.0001,
                                    validation_fraction=0.1, verbose=False,
                                    warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'activation': ['relu', 'logistic'],
             

In [53]:
mlp_cv_model.best_params_

{'activation': 'relu', 'alpha': 0.005, 'hidden_layer_sizes': (100, 50, 150)}

In [54]:
mlp_tuned = MLPRegressor(alpha = 0.005, hidden_layer_sizes = (100, 50, 150), activation = "relu")

In [55]:
mlp_tuned.fit(X_train_scaled, y_train)

MLPRegressor(activation='relu', alpha=0.005, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100, 50, 150), learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=None, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [57]:
y_pred_test = mlp_tuned.predict(X_test_scaled)

y_pred_test

array([ 491.11340185,  748.53547353, 1084.76235757,  617.00403721,
        450.85574935,  294.41271686,  634.02574417,  445.97326295,
        984.00926573,  597.49068358,  655.60659185,  938.65304515,
        553.77442179,  745.13720688,  235.40188063,  654.42408746,
        989.87228021,  249.83207189, 1139.23201114,  227.20837458,
        334.09464892,  888.46336365,  491.48007904,  521.10888329,
        970.5100819 ,  234.0598617 ,  685.80805602,  219.12812225,
        535.80765248,  288.04673056,  250.4147414 ,  422.59455166,
        275.98852075,  408.04299639,  265.0812525 ,  539.6482647 ,
       1509.08705125,  180.44847846,  353.82890983,  311.7651089 ,
        222.50509767,  219.59438784,  381.52758118,  301.30905246,
       1034.83121919,  740.86508068,  440.21202821,  203.69536595,
        253.41788333,  727.90135343,  756.517764  ,  360.08267707,
        612.7090506 ,  297.36832865,  258.51266416,  737.0598864 ,
        416.19396073,  664.58202142,  327.38143092, 1486.20279

In [59]:
np.sqrt(mean_squared_error(y_test, y_pred_test))

357.7209481497497

-------------